### ISSUE TITLE
All interactive elements should have special behaviour while hovering over them, focusing on 

### ISSUE THREAD

**Issue by heywhahappnd** [YuriiMatsiv/SweetsProject#1]
1)Input doesn't change
2)icons don't change
3)buttons with LINK text don't change
4)button Всі 309 Цукерочок doesn't change

**Comment by YuriiMatsiv** [comment]
Fixed

**Comment by heywhahappnd** [comment]
У стрелки в инпуте тоже должно меняться поведение , в макете вроде описано, как именно

**Comment by heywhahappnd** [comment]
1) У стрелки в инпуте ничего не поменялось
2)Когда пишешь внутри input текст не должен быть зелёным.
3)Когда вводишь не валидную почту - должно меняться поведение. Посмотри в примере

**Comment by YuriiMatsiv** [comment]
Тільки щось ну ніяк в мене не получається,  щоб при кліку - було біле поле...
